# quiz_bank.py
# ─────────────────────────────────────────────────────────────────────────────
# Bộ câu hỏi Quiz mở rộng — phân nhóm theo triết lý app.
# Mỗi câu: giải thích (explain) cho cả đúng/sai + bias_map (đáp án sai → mã bias)
# để nuôi 🪞 Tấm gương. Mã bias dùng bộ chuẩn: FOMO, HERD, OVERCONFIDENCE,
# ACTION, OUTCOME, REVENGE, NO_STOP, OVERSIZE, IGNORE_REGIME.
# Cấu trúc giữ tương thích: q_vi/q_en, options_vi/en, answer_vi/en, bias_map_vi/en
# (thêm explain_vi/explain_en).
# ─────────────────────────────────────────────────────────────────────────────


def _q(qvi, qen, ovi, oen, avi, aen, exvi, exen, bvi=None, ben=None):
    return {
        "q_vi": qvi, "q_en": qen,
        "options_vi": ovi, "options_en": oen,
        "answer_vi": avi, "answer_en": aen,
        "explain_vi": exvi, "explain_en": exen,
        "bias_map_vi": bvi or {}, "bias_map_en": ben or {},
    }


QUIZ_BANK = {
    # ═══ RISK FIRST ═══════════════════════════════════════════════════════════
    "Risk First — Phòng thủ": [
        _q("Câu hỏi ĐẦU TIÊN trước khi vào lệnh nên là gì?",
           "What is the FIRST question before entering a trade?",
           ["Tôi có thể lãi bao nhiêu?", "Nếu sai, tôi mất bao nhiêu?", "Ai đang mua mã này?"],
           ["How much can I gain?", "If wrong, how much do I lose?", "Who else is buying this?"],
           "Nếu sai, tôi mất bao nhiêu?", "If wrong, how much do I lose?",
           "Risk First: xác định mức mất trước khi nghĩ tới lãi. Sống sót quan trọng hơn lãi nhanh.",
           "Risk First: define your downside before the upside. Survival beats fast gains.",
           {"Tôi có thể lãi bao nhiêu?": "FOMO", "Ai đang mua mã này?": "HERD"},
           {"How much can I gain?": "FOMO", "Who else is buying this?": "HERD"}),
        _q("Rủi ro tối đa hợp lý cho MỖI lệnh là khoảng?",
           "A reasonable maximum risk PER trade is about?",
           ["Không cần giới hạn", "~1–2% tài khoản", "~20% để lãi nhanh"],
           ["No limit needed", "~1–2% of account", "~20% for fast gains"],
           "~1–2% tài khoản", "~1–2% of account",
           "Giới hạn rủi ro nhỏ mỗi lệnh giúp bạn sống sót qua chuỗi thua không tránh khỏi.",
           "Small per-trade risk lets you survive the inevitable losing streaks.",
           {"Không cần giới hạn": "OVERSIZE", "~20% để lãi nhanh": "OVERSIZE"},
           {"No limit needed": "OVERSIZE", "~20% for fast gains": "OVERSIZE"}),
        _q("Nhà đầu tư sống sót lâu dài nhờ điều gì?",
           "What lets an investor survive long term?",
           ["Luôn luôn đúng", "Sai nhưng không chết", "Dùng đòn bẩy cao"],
           ["Always being right", "Being wrong without dying", "Using high leverage"],
           "Sai nhưng không chết", "Being wrong without dying",
           "Không ai luôn đúng. Người trụ lại là người khi sai vẫn không mất sạch vốn.",
           "Nobody is always right. Survivors are those who don't get wiped out when wrong.",
           {"Luôn luôn đúng": "OVERCONFIDENCE", "Dùng đòn bẩy cao": "OVERSIZE"},
           {"Always being right": "OVERCONFIDENCE", "Using high leverage": "OVERSIZE"}),
        _q("Điểm dừng lỗ (stop-loss) nên xác định khi nào?",
           "When should you decide your stop-loss?",
           ["Sau khi vào lệnh, nếu thấy lỗ", "TRƯỚC khi vào lệnh", "Không cần nếu tin vào mã"],
           ["After entering, if it drops", "BEFORE entering", "Not needed if you trust the stock"],
           "TRƯỚC khi vào lệnh", "BEFORE entering",
           "Xác định điểm thoát trước khi vào = quyết định lúc đầu óc tỉnh táo, không phải lúc hoảng loạn.",
           "Define the exit before entry = decide while calm, not while panicking.",
           {"Sau khi vào lệnh, nếu thấy lỗ": "NO_STOP", "Không cần nếu tin vào mã": "NO_STOP"},
           {"After entering, if it drops": "NO_STOP", "Not needed if you trust the stock": "NO_STOP"}),
        _q("Một lệnh đang LÃI to nhưng lúc vào quy trình sai (may mắn). Bạn nên?",
           "A trade is up big but the entry process was flawed (luck). You should?",
           ["Tự tin lặp lại cách đó", "Nhận ra đó là may, không lặp lại", "Tăng size lần sau"],
           ["Confidently repeat it", "Recognize it was luck, don't repeat", "Size up next time"],
           "Nhận ra đó là may, không lặp lại", "Recognize it was luck, don't repeat",
           "Đánh giá quyết định bằng QUY TRÌNH, không bằng kết quả. Lãi nhờ sai quy trình là rủi ro dài hạn.",
           "Judge decisions by PROCESS, not outcome. Profit from a bad process is long-term risk.",
           {"Tự tin lặp lại cách đó": "OUTCOME", "Tăng size lần sau": "OUTCOME"},
           {"Confidently repeat it": "OUTCOME", "Size up next time": "OUTCOME"}),
        _q("\"Phòng thủ trước rồi tấn công sau\" nghĩa là?",
           "\"Defend first, then attack\" means?",
           ["Chỉ phòng thủ, không bao giờ mua", "Ưu tiên kiểm soát rủi ro trước khi tìm lợi nhuận", "Chờ đáy tuyệt đối"],
           ["Only defend, never buy", "Control risk first, then seek returns", "Wait for the absolute bottom"],
           "Ưu tiên kiểm soát rủi ro trước khi tìm lợi nhuận", "Control risk first, then seek returns",
           "Không phải không tấn công — mà là bảo toàn vốn trước, để còn vốn mà tấn công khi cơ hội đến.",
           "Not 'never attack' — preserve capital first so you still have capital to attack when the chance comes.",
           None, None),
    ],

    # ═══ REGIME FIRST (VN) ════════════════════════════════════════════════════
    "Regime First — Việt Nam": [
        _q("Setup kỹ thuật ĐẸP nhưng regime đang Risk-off. Bạn nên?",
           "A GREAT technical setup but the regime is Risk-off. You should?",
           ["Mua vì setup đẹp", "No-Trade, chờ regime cải thiện", "Mua test size thật lớn"],
           ["Buy — the setup is great", "No-Trade, wait for regime to improve", "Buy a large 'test' size"],
           "No-Trade, chờ regime cải thiện", "No-Trade, wait for regime to improve",
           "Regime First: regime quyết định bạn CÓ chơi không. Setup đẹp trong Risk-off vẫn là No-Trade.",
           "Regime First: the regime decides WHETHER you play. A great setup in Risk-off is still No-Trade.",
           {"Mua vì setup đẹp": "IGNORE_REGIME", "Mua test size thật lớn": "IGNORE_REGIME"},
           {"Buy — the setup is great": "IGNORE_REGIME", "Buy a large 'test' size": "IGNORE_REGIME"}),
        _q("Tín hiệu nào ĐẶC THÙ thường đè VN-Index mạnh khi kéo dài?",
           "Which VN-SPECIFIC signal often pressures VN-Index when it persists?",
           ["Khối ngoại bán ròng mạnh kéo dài", "Giá vàng thế giới", "Lãi suất trái phiếu Đức"],
           ["Heavy sustained foreign net selling", "Global gold price", "German bond yields"],
           "Khối ngoại bán ròng mạnh kéo dài", "Heavy sustained foreign net selling",
           "Dòng vốn ngoại là đặc thù lớn của TTCK VN — bán ròng kéo dài tạo lực bán cấu trúc.",
           "Foreign flows are a major VN-specific driver — sustained selling creates structural pressure.",
           None, None),
        _q("\"Force-sell (giải chấp) đang xảy ra\" → regime là?",
           "\"Force-selling in progress\" → the regime is?",
           ["Risk-on, vì giá đang rẻ", "Risk-off (VETO)", "Risk-on nếu VN-Index trên MA200"],
           ["Risk-on, prices are cheap", "Risk-off (VETO)", "Risk-on if VN-Index is above MA200"],
           "Risk-off (VETO)", "Risk-off (VETO)",
           "Force-sell ép thẳng Risk-off bất kể điểm số. Rẻ không phải lý do mua khi giải chấp dây chuyền chưa dứt.",
           "Force-selling forces Risk-off regardless of score. Cheap isn't a reason to buy mid-cascade.",
           {"Risk-on, vì giá đang rẻ": "IGNORE_REGIME", "Risk-on nếu VN-Index trên MA200": "IGNORE_REGIME"},
           {"Risk-on, prices are cheap": "IGNORE_REGIME", "Risk-on if VN-Index is above MA200": "IGNORE_REGIME"}),
        _q("VN-Index trên MA200, mọi thứ tốt, nhưng BREADTH yếu (ít mã dẫn). Regime?",
           "VN-Index above MA200, all good, but BREADTH is weak (few leaders). Regime?",
           ["Risk-on", "Mixed (bị CAP vì breadth)", "Risk-off"],
           ["Risk-on", "Mixed (CAP-ped on breadth)", "Risk-off"],
           "Mixed (bị CAP vì breadth)", "Mixed (CAP-ped on breadth)",
           "Rally không có độ rộng thì chưa phải uptrend thật. Breadth là cổng bắt buộc để lên Risk-on.",
           "A rally without breadth isn't a real uptrend. Breadth is the mandatory gate to Risk-on.",
           None, None),
        _q("Dư nợ margin toàn thị trường ĐANG TĂNG mạnh nghĩa là?",
           "Market-wide margin debt RISING sharply means?",
           ["An toàn, nhiều người tin tưởng", "Rủi ro đòn bẩy đang tích tụ", "Không liên quan đến rủi ro"],
           ["Safe — lots of confidence", "Leverage risk is building up", "Unrelated to risk"],
           "Rủi ro đòn bẩy đang tích tụ", "Leverage risk is building up",
           "Margin cao là nhiên liệu cho giải chấp dây chuyền khi thị trường quay đầu. Đỉnh margin thường gần đỉnh giá.",
           "High margin is fuel for a force-sell cascade on a turn. Margin peaks often sit near price peaks.",
           {"An toàn, nhiều người tin tưởng": "OVERCONFIDENCE"},
           {"Safe — lots of confidence": "OVERCONFIDENCE"}),
        _q("Tỷ giá USD/VND căng thẳng ảnh hưởng TTCK VN chủ yếu qua?",
           "USD/VND stress affects VN stocks mainly through?",
           ["Khối ngoại rút vốn + SBV buộc siết chính sách", "Không ảnh hưởng gì", "Chỉ ảnh hưởng cổ phiếu xuất khẩu"],
           ["Foreign outflows + SBV forced to tighten", "No effect at all", "Only export stocks"],
           "Khối ngoại rút vốn + SBV buộc siết chính sách", "Foreign outflows + SBV forced to tighten",
           "VND mất giá mạnh → vốn ngoại rút, SBV có thể siết thanh khoản — cả hai đều là gió ngược cho cổ phiếu.",
           "Sharp VND depreciation → foreign outflows and possible SBV tightening — both headwinds for stocks.",
           None, None),
    ],

    # ═══ REGIME FIRST (US) ════════════════════════════════════════════════════
    "Regime First — Mỹ (US)": [
        _q("Ở thị trường Mỹ, chỉ số 'sợ hãi' chính là?",
           "In the US market, the main 'fear' index is?",
           ["VN-Index", "VIX", "DXY (chỉ số USD)"],
           ["VN-Index", "VIX", "DXY (dollar index)"],
           "VIX", "VIX",
           "VIX đo biến động kỳ vọng của S&P 500 — thước đo sợ hãi chính của Mỹ. >28 căng, >40 hoảng loạn.",
           "VIX measures expected S&P 500 volatility — the primary US fear gauge. >28 stress, >40 panic.",
           None, None),
        _q("Chênh lệch tín dụng High-Yield (HY) NỚI RỘNG báo hiệu?",
           "WIDENING high-yield (HY) credit spreads signal?",
           ["Thị trường nợ đang cảnh báo rủi ro", "Cổ phiếu chắc chắn sắp tăng", "Không có ý nghĩa"],
           ["The debt market is flagging risk", "Stocks will surely rise", "No meaning"],
           "Thị trường nợ đang cảnh báo rủi ro", "The debt market is flagging risk",
           "Thị trường tín dụng thường 'thấy' rủi ro trước cổ phiếu. Spread nới rộng = tiền tháo khỏi rủi ro.",
           "Credit often 'sees' risk before equities. Widening spreads = money fleeing risk.",
           None, None),
        _q("Fed đang thắt chặt MẠNH. Nguyên tắc 'Don't fight the Fed' khuyên?",
           "The Fed is tightening HARD. 'Don't fight the Fed' advises?",
           ["Tăng rủi ro vì giá đã giảm", "Giảm rủi ro — Fed đang hút thanh khoản", "Bỏ qua Fed, chỉ nhìn biểu đồ"],
           ["Add risk since prices fell", "Cut risk — the Fed is draining liquidity", "Ignore the Fed, just read charts"],
           "Giảm rủi ro — Fed đang hút thanh khoản", "Cut risk — the Fed is draining liquidity",
           "Khi NHTW hút thanh khoản, môi trường nghịch với rủi ro. Đừng chống lại dòng chảy thanh khoản.",
           "When the central bank drains liquidity, the environment is hostile to risk. Don't fight the liquidity tide.",
           {"Tăng rủi ro vì giá đã giảm": "IGNORE_REGIME", "Bỏ qua Fed, chỉ nhìn biểu đồ": "IGNORE_REGIME"},
           {"Add risk since prices fell": "IGNORE_REGIME", "Ignore the Fed, just read charts": "IGNORE_REGIME"}),
        _q("Đường cong lợi suất 10Y–2Y ĐẢO NGƯỢC thường là?",
           "An INVERTED 10Y–2Y yield curve is usually?",
           ["Tín hiệu suy thoái kinh điển", "Tín hiệu mua mạnh ngay", "Một lỗi dữ liệu"],
           ["A classic recession signal", "An immediate strong-buy", "A data error"],
           "Tín hiệu suy thoái kinh điển", "A classic recession signal",
           "Đảo ngược đường cong báo suy thoái — nhưng thường đi TRƯỚC nhiều tháng, không phải tín hiệu bán ngay.",
           "Inversion warns of recession — but usually leads by many months, not an immediate sell.",
           None, None),
        _q("S&P 500 tăng nhưng chỉ vài siêu cổ phiếu (megacap) kéo. Regime?",
           "S&P 500 rises but only a few megacaps carry it. Regime?",
           ["Risk-on mạnh", "Mixed (rally hẹp)", "Risk-off"],
           ["Strong Risk-on", "Mixed (narrow rally)", "Risk-off"],
           "Mixed (rally hẹp)", "Mixed (narrow rally)",
           "Rally hẹp dựa vào vài megacap rất dễ gãy — đặc trưng cảnh báo của thị trường Mỹ. Breadth yếu → CAP về Mixed.",
           "A narrow megacap-led rally is fragile — a hallmark US warning. Weak breadth → CAP to Mixed.",
           None, None),
        _q("Regime VN và US có nên dùng CÙNG một bộ tín hiệu?",
           "Should VN and US regimes use the SAME signal set?",
           ["Có, thị trường nào cũng như nhau", "Không — mỗi thị trường có tín hiệu đặc thù", "Chỉ cần VIX là đủ cho cả hai"],
           ["Yes, all markets are alike", "No — each market has its own drivers", "VIX alone suffices for both"],
           "Không — mỗi thị trường có tín hiệu đặc thù", "No — each market has its own drivers",
           "VN nặng về khối ngoại/margin CTCK/SBV; US nặng về VIX/credit spread/Fed/yield curve. Trộn lẫn = mất chính xác.",
           "VN leans on foreign flows/broker margin/SBV; US on VIX/credit/Fed/curve. Mixing them loses accuracy.",
           None, None),
    ],

    # ═══ EVIDENCE FIRST & GOVERNANCE ══════════════════════════════════════════
    "Evidence First & Kỷ luật": [
        _q("Regime chuyển Risk-on → Mixed thường được BÁO TRƯỚC bởi?",
           "A Risk-on → Mixed shift is usually PRECEDED by?",
           ["Một tin tức bất ngờ duy nhất", "Risk-on Score trượt dần qua nhiều tuần", "Không thể biết trước"],
           ["A single surprise headline", "The Risk-on Score drifting down over weeks", "It's unpredictable"],
           "Risk-on Score trượt dần qua nhiều tuần", "The Risk-on Score drifting down over weeks",
           "Regime hiếm khi đổi đột ngột. Điểm trượt dần (vd 86→78→71) là cảnh báo sớm — phản ứng với xu hướng, không chờ nhãn.",
           "Regime rarely flips abruptly. A drifting score (e.g. 86→78→71) is the early warning — react to the trend, not the label.",
           None, None),
        _q("Rubric tính Risk-on nhưng admin ghi đè thủ công thành Risk-off. App nên?",
           "The rubric computes Risk-on but the admin manually overrides to Risk-off. The app should?",
           ["Giấu việc ghi đè cho gọn", "Công khai việc ghi đè", "Xóa luôn rubric"],
           ["Hide the override for tidiness", "Disclose the override", "Delete the rubric"],
           "Công khai việc ghi đè", "Disclose the override",
           "Evidence First = minh bạch. Người dùng cần biết khi kết luận khác với rubric, để tự đánh giá.",
           "Evidence First = transparency. Users must know when a call differs from the rubric, to judge for themselves.",
           None, None),
        _q("\"Evidence First\" nghĩa là?",
           "\"Evidence First\" means?",
           ["Tin theo cảm giác thị trường", "Quyết định dựa trên bằng chứng kiểm chứng được", "Nghe theo chuyên gia nổi tiếng"],
           ["Trust the market 'feel'", "Decide on verifiable evidence", "Follow famous experts"],
           "Quyết định dựa trên bằng chứng kiểm chứng được", "Decide on verifiable evidence",
           "Quyết định phải tựa vào dữ liệu kiểm chứng được, tái lập được — không phải cảm giác hay uy tín người nói.",
           "Decisions rest on verifiable, reproducible data — not feel or the speaker's reputation.",
           {"Nghe theo chuyên gia nổi tiếng": "HERD"},
           {"Follow famous experts": "HERD"}),
        _q("No-Trade (không giao dịch) là?",
           "No-Trade (choosing not to trade) is?",
           ["Dấu hiệu yếu kém, thiếu quyết đoán", "Một quyết định hợp lệ", "Luôn luôn sai"],
           ["A sign of weakness", "A valid decision", "Always wrong"],
           "Một quyết định hợp lệ", "A valid decision",
           "Không phải ngày nào cũng phải vào lệnh. Đứng ngoài khi không có lợi thế là kỷ luật, không phải yếu kém.",
           "You don't have to trade every day. Standing aside without an edge is discipline, not weakness.",
           {"Dấu hiệu yếu kém, thiếu quyết đoán": "ACTION"},
           {"A sign of weakness": "ACTION"}),
        _q("Kỷ luật (governance) quan trọng vì?",
           "Why does governance (discipline) matter?",
           ["Giúp lãi nhanh hơn", "Giữ bạn nhất quán, không phá luật lúc cảm xúc", "Thay thế cho phân tích"],
           ["It speeds up gains", "It keeps you consistent, not breaking rules under emotion", "It replaces analysis"],
           "Giữ bạn nhất quán, không phá luật lúc cảm xúc", "It keeps you consistent, not breaking rules under emotion",
           "Phân tích đúng vô nghĩa nếu bạn phá luật lúc sợ/tham. Kỷ luật giữ cho hành động khớp với kế hoạch.",
           "Good analysis is useless if you break rules under fear/greed. Discipline keeps actions aligned with the plan.",
           None, None),
    ],

    # ═══ TÂM LÝ & BIAS ════════════════════════════════════════════════════════
    "Tâm lý & Bias": [
        _q("Mua đuổi một mã đã tăng mạnh vì sợ lỡ sóng là?",
           "Chasing a stock that already ran up, for fear of missing out, is?",
           ["FOMO", "Phân tích kỹ lưỡng", "Kỷ luật tốt"],
           ["FOMO", "Thorough analysis", "Good discipline"],
           "FOMO", "FOMO",
           "FOMO khiến bạn vào ở vùng giá xấu, đúng lúc người vào sớm thoát hàng. Đuổi giá = bỏ Risk First.",
           "FOMO makes you enter at a bad price, just as early buyers exit. Chasing = abandoning Risk First.",
           {"Phân tích kỹ lưỡng": "FOMO", "Kỷ luật tốt": "FOMO"},
           {"Thorough analysis": "FOMO", "Good discipline": "FOMO"}),
        _q("Sau chuỗi lỗ, vào một lệnh thật lớn để 'gỡ' lại là?",
           "After a losing streak, taking a big trade to 'win it back' is?",
           ["Revenge trading", "Quản trị vốn tốt", "Bình tĩnh"],
           ["Revenge trading", "Good money management", "Staying calm"],
           "Revenge trading", "Revenge trading",
           "Vào lệnh khi đang tức là lỗi cảm xúc nguy hiểm nhất. Sau khi lỗ: DỪNG, không gỡ gạc.",
           "Trading while angry is the most dangerous emotional error. After a loss: STOP, don't chase revenge.",
           {"Quản trị vốn tốt": "REVENGE", "Bình tĩnh": "REVENGE"},
           {"Good money management": "REVENGE", "Staying calm": "REVENGE"}),
        _q("Cảm giác 'Tôi CHẮC CHẮN mã này sẽ tăng' là dấu hiệu nên?",
           "Feeling 'I'm CERTAIN this will go up' is a cue to?",
           ["Tăng size cho mạnh", "Giảm size — đó là tự tin thái quá", "Vay margin tối đa"],
           ["Size up hard", "Cut size — that's overconfidence", "Max out margin"],
           "Giảm size — đó là tự tin thái quá", "Cut size — that's overconfidence",
           "Thị trường là xác suất, không có 'chắc chắn'. Cảm giác chắc ăn là lúc dễ mất cảnh giác nhất.",
           "Markets are probabilities; 'certainty' doesn't exist. Feeling sure is when you're least careful.",
           {"Tăng size cho mạnh": "OVERCONFIDENCE", "Vay margin tối đa": "OVERSIZE"},
           {"Size up hard": "OVERCONFIDENCE", "Max out margin": "OVERSIZE"}),
        _q("Bán mã đang LÃI quá sớm nhưng GIỮ mã lỗ quá lâu là biểu hiện của?",
           "Selling winners too early but holding losers too long reflects?",
           ["Sợ lỗ (loss aversion)", "Kỷ luật chốt lời", "Chiến lược hợp lý"],
           ["Loss aversion", "Disciplined profit-taking", "A sound strategy"],
           "Sợ lỗ (loss aversion)", "Loss aversion",
           "Bộ não ghét hiện thực hóa lỗ nên ôm mã lỗ; lại sợ mất lãi nên chốt sớm. Cả hai đều phá vỡ tỷ lệ lời/lỗ.",
           "The brain hates realizing losses (holds losers) and fears losing gains (cuts winners). Both wreck your reward/risk.",
           None, None),
        _q("Vào một mã chỉ vì 'cả room đang hô, nhiều người mua' là?",
           "Buying a stock just because 'the whole group is hyping it' is?",
           ["Theo đám đông (Herd)", "Nghiên cứu độc lập", "Evidence First"],
           ["Herd mentality", "Independent research", "Evidence First"],
           "Theo đám đông (Herd)", "Herd mentality",
           "Đám đông sai ở đỉnh và đáy. Quyết định theo bằng chứng của BẠN, không theo tiếng hô.",
           "The crowd is wrong at tops and bottoms. Decide on YOUR evidence, not the noise.",
           {"Nghiên cứu độc lập": "HERD", "Evidence First": "HERD"},
           {"Independent research": "HERD", "Evidence First": "HERD"}),
        _q("Cảm xúc nào nguy hiểm nhất khi bạn đang THẮNG liên tục?",
           "Which emotion is most dangerous during a WINNING streak?",
           ["Hưng phấn → oversize ('tiền nhà cái')", "Sợ hãi", "Không có cảm xúc nào nguy hiểm"],
           ["Euphoria → oversizing ('house money')", "Fear", "No dangerous emotion"],
           "Hưng phấn → oversize ('tiền nhà cái')", "Euphoria → oversizing ('house money')",
           "Phần lớn tài khoản cháy lúc THẮNG, không phải lúc thua: thắng vài lệnh → hưng phấn → đặt cược quá lớn → một cú nổ.",
           "Most accounts blow up while WINNING, not losing: a few wins → euphoria → oversized bets → one blow-up.",
           {"Sợ hãi": "OVERCONFIDENCE"},
           {"Fear": "OVERCONFIDENCE"}),
    ],

    # ═══ LỖI THỰC THI ═════════════════════════════════════════════════════════
    "Lỗi thực thi": [
        _q("Mua thêm mã ĐANG LỖ để 'hạ giá vốn', không có điểm dừng, là?",
           "Buying more of a LOSING stock to 'lower your cost', with no stop, is?",
           ["Bình quân giá xuống nguy hiểm", "Scaling-in có kế hoạch", "Một nước đi khôn ngoan"],
           ["Dangerous averaging down", "Planned scaling-in", "A smart move"],
           "Bình quân giá xuống nguy hiểm", "Dangerous averaging down",
           "Ném tiền tốt theo tiền xấu, biến lỗ nhỏ thành lỗ thảm họa. Khác scaling-in có sẵn mức VÀ invalidation.",
           "Throwing good money after bad, turning a small loss into a catastrophic one. Unlike scaling-in with preset levels AND an invalidation.",
           {"Scaling-in có kế hoạch": "NO_STOP", "Một nước đi khôn ngoan": "NO_STOP"},
           {"Planned scaling-in": "NO_STOP", "A smart move": "NO_STOP"}),
        _q("Trước khi vào lệnh, một kế hoạch tối thiểu cần viết ra gồm?",
           "A minimal pre-trade plan should write down?",
           ["Lý do vào, invalidation, mục tiêu, size", "Chỉ cần biết mã nào", "Không cần gì, vào theo cảm giác"],
           ["Entry reason, invalidation, target, size", "Just the ticker", "Nothing — go by feel"],
           "Lý do vào, invalidation, mục tiêu, size", "Entry reason, invalidation, target, size",
           "Không viết được 4 thứ đó = chưa đủ rõ để vào. Vào vì lý do, ra vì lý do — không vì cảm xúc.",
           "If you can't write those four, it's not clear enough to enter. Enter for a reason, exit for a reason.",
           {"Không cần gì, vào theo cảm giác": "NO_STOP"},
           {"Nothing — go by feel": "NO_STOP"}),
        _q("Giao dịch nhiều lần MỖI NGÀY — vấn đề lớn nhất thường là?",
           "Trading many times EACH DAY — the biggest problem usually is?",
           ["Phí + thuế bào mòn (chết bởi ngàn nhát cắt)", "Lãi nhanh hơn hẳn", "Không có vấn đề gì"],
           ["Fees + tax erosion (death by a thousand cuts)", "Much faster gains", "No problem at all"],
           "Phí + thuế bào mòn (chết bởi ngàn nhát cắt)", "Fees + tax erosion (death by a thousand cuts)",
           "Mỗi vòng mất phí + thuế (~0.4%). Giao dịch nhiều = phí ăn sâu + nhiều cơ hội mắc lỗi cảm xúc. Ít mà chất.",
           "Each round trip costs fees + tax (~0.4%). More trades = deeper cost drag + more emotional errors. Fewer, better.",
           {"Lãi nhanh hơn hẳn": "ACTION", "Không có vấn đề gì": "ACTION"},
           {"Much faster gains": "ACTION", "No problem at all": "ACTION"}),
        _q("Đặt stop-loss rồi NỚI nó ra xa khi giá tới gần vì 'rồi sẽ hồi' là?",
           "Setting a stop then WIDENING it as price approaches, because 'it'll come back', is?",
           ["Lỗi nguy hiểm — xóa sạch quản trị rủi ro", "Linh hoạt thông minh", "Bình thường, ai cũng làm"],
           ["A dangerous error — it erases risk management", "Smart flexibility", "Normal, everyone does it"],
           "Lỗi nguy hiểm — xóa sạch quản trị rủi ro", "A dangerous error — it erases risk management",
           "Stop đã đặt là cam kết. Dời stop theo cảm xúc biến một lỗ nhỏ có kiểm soát thành lỗ vô hạn.",
           "A placed stop is a commitment. Moving it on emotion turns a small controlled loss into an unbounded one.",
           {"Linh hoạt thông minh": "NO_STOP", "Bình thường, ai cũng làm": "NO_STOP"},
           {"Smart flexibility": "NO_STOP", "Normal, everyone does it": "NO_STOP"}),
        _q("Một 'kèo' được phát MIỄN PHÍ và CÔNG KHAI nghĩa là bạn?",
           "A tip handed out FREE and PUBLICLY means you are?",
           ["Khách hàng VIP được ưu ái", "Thanh khoản thoát hàng cho người vào trước", "Người may mắn"],
           ["A favored VIP customer", "Exit liquidity for whoever entered first", "Just lucky"],
           "Thanh khoản thoát hàng cho người vào trước", "Exit liquidity for whoever entered first",
           "Bạn nhận tin sau cùng, không biết luận điểm nên không biết khi nào sai, không size được. Đu phím = làm mồi.",
           "You get the info last, don't know the thesis (so can't know when it's wrong), can't size it. Following tips = being the bait.",
           {"Khách hàng VIP được ưu ái": "HERD", "Người may mắn": "HERD"},
           {"A favored VIP customer": "HERD", "Just lucky": "HERD"}),
        _q("Dồn phần lớn tài khoản vào MỘT mã duy nhất là?",
           "Putting most of your account into a SINGLE stock is?",
           ["Tối ưu lợi nhuận", "Rủi ro một điểm chí mạng", "An toàn vì bạn hiểu rõ mã đó"],
           ["Optimizing returns", "Single-point catastrophic risk", "Safe because you know it well"],
           "Rủi ro một điểm chí mạng", "Single-point catastrophic risk",
           "Một cú nổ đơn lẻ (gian lận, tin xấu, sàn) có thể xóa sổ tài khoản. Đủ ít để hiểu, đủ nhiều để SỐNG SÓT.",
           "One single blow-up (fraud, bad news, halt) can wipe the account. Few enough to know, many enough to SURVIVE.",
           {"Tối ưu lợi nhuận": "OVERSIZE", "An toàn vì bạn hiểu rõ mã đó": "OVERSIZE"},
           {"Optimizing returns": "OVERSIZE", "Safe because you know it well": "OVERSIZE"}),
    ],
}
